### ISSUE TITLE
Plugin could not be activated because it triggered a fatal error.

### ISSUE THREAD

**Issue by ghost** [getbowtied/shopkeeper-extender#2]
Plugin could not be activated because it triggered a fatal error.

Fatal error: Cannot declare class rc_sweet_custom_menu, because the name is already in use in

/wp-content/plugins/shopkeeper-extender/includes/custom-menu/custom-menu.php on line 14

after update DO NOT ACTIVE

**Comment by rthvanesa** [comment]
Hi @wpCache, thanks for reaching out!

Please make sure you have the latest theme version (2.8.6) along with the latest Shopkeeper Extender plugin (we have just released version 1.4.8 which I hope solves the problem) and give it a try again. 

Let me know how's everything working after that.

Have a good one!
Vanesa

**Comment by ghost** [comment]
theme version 2.8.5  / 1.4.6

The site is experiencing technical difficulties. Please check your site admin email inbox for instructions.

theme version 2.8.6  / 1.4.8

ok working
