### ISSUE TITLE
Can you update?

### ISSUE THREAD

**Issue by budtanical** [getbowtied/shopkeeper-extender#3]
Hi there, I was having issues installing the update.  I got this:
Shopkeeper ExtenderDeactivate \| Resume | Extends the functionality of Shopkeeper with Gutenberg elements. 						Version 1.2 \| By GetBowtied \| Visit plugin site This plugin failed to load properly and is paused during recovery mode.An error of type E_ERROR was caused in line 48 of the file /home1/sowngrow/public_html/budtanicals.net/wp-content/plugins/shopkeeper-extender/shopkeeper-extender.php. Error message: Class 'WP_GitHub_Updater' not found
-- | --

So I contacted blue host because I was unable to install it in recovery mode as it paused during installation because it detected that there was an error.  Bluehost Support staff  told me to relay this to you: "I will provide server requirements please provide these settings to plugin provider to update, once they update there will be no further issues:  cPanel 78.0 (build 30) Apache 2.4.39 PHP 5.6.40 MySQL 5.6.41-84.1 Perl 5.28.0    Can you help?

-- | --

**Comment by rthvanesa** [comment]
Hello @budtanical,

Can't think what went wrong there, I can only think some file got corrupted when the plugin got installed or updated. You can simply delete the plugin then reinstall the latest version. You can do that via **Appearance** > **Install plugins**. That should do it. Please let me know if you run into any other issues.

Cheers,
Vanesa
