### ISSUE TITLE
crashes website after update

### ISSUE THREAD

**Issue by truesamurai** [getbowtied/shopkeeper-extender#6]
Today I updated the Shopkeeper Extended plugin on a website with the latest WordPress version. But after the update the website crashed (error was: unexpected error) so I had to revert back to previous state.

**Comment by kitserve** [comment]
Duplicate of #5. See there for a manual fix by editing the buggy file. Request @romi-getbowtied to push out the fix officially asap before more sites break!

**Comment by rthvanesa** [comment]
Hello @sh1va73 ,

We are sorry for the inconvenience. We believe this error occurs only for Shopkeeper theme versions older than 2.8. However, we have applied a fix and released Shopkeeper Extender 1.6.3. 

Please let me know if you encounter any other issues. 

Have a good one!
