### ISSUE TITLE
Duplicate Open Graph image, og:image

### ISSUE THREAD

**Issue by 0xmarc0** [getbowtied/shopkeeper-extender#7]
Hello, we had some trouble choosing and updating facebook of:image because of duplicate of:image meta. We use a dedicated SEO and Open Graph Image Plugin that lets us choose the of:image, but that was ignored.

I believe it would be better to either remove of:image meta from shopkeeper-extender or have an option to disable it.

**Comment by rthvanesa** [comment]
Hi @gottschild,

I'm sorry for the late reply. As you have requested and probably seen in the latest update's changelog, we have introduced an option to enable/disable the default Facebook Open Graph for product pages. I hope this solved your compatibility issue.

Please let me know if you encounter any other issues.

Have a good one!
